language: objective-c
before_install:
  - brew update
install:
  - mkdir -p $(brew --repo)/Library/Taps
  - ln -s $PWD $(brew --repo)/Library/Taps/azukiapp-azk
  - brew tap --repair
script:
  - brew audit azk
  - brew install -v azk
matrix:
  fast_finish: true
